// <auto-generated />
using System;
using BCP.Auth.API.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BCP.Auth.API.Infrastructure.Persistence.Migrations;

[DbContext(typeof(AuthDbContext))]
partial class AuthDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("auth")
            .HasAnnotation("ProductVersion", "8.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("BCP.Auth.API.Domain.Entities.Usuario", b =>
        {
            b.Property<Guid>("IdUsuario")
                .HasColumnType("uniqueidentifier");

            b.Property<DateTime>("FechaCreacion")
                .HasColumnType("datetime2");

            b.Property<Guid?>("IdEmpresa")
                .HasColumnType("uniqueidentifier");

            b.Property<Guid?>("IdSucursal")
                .HasColumnType("uniqueidentifier");

            b.Property<string>("Nombre")
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnType("nvarchar(200)");

            b.Property<string>("Email")
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnType("nvarchar(200)");

            b.Property<string>("PasswordHash")
                .IsRequired()
                .HasMaxLength(500)
                .HasColumnType("nvarchar(500)");

            b.Property<string>("Rol")
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnType("nvarchar(50)");

            b.Property<string>("Estado")
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("Activo")
                .HasColumnType("nvarchar(20)");

            b.Property<DateTime?>("UltimoAcceso")
                .HasColumnType("datetime2");

            b.HasKey("IdUsuario");

            b.HasIndex("Email")
                .IsUnique();

            b.ToTable("Usuario", "auth");
        });
#pragma warning restore 612, 618
    }
}
